//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wep_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Company_SlNo { get; set; }
        public string Company_Name { get; set; }
        public string Company_Description { get; set; }
        public byte[] Company_Logo { get; set; }
    }
}
