//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wep_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBranch
    {
        public int Branch_SlNo { get; set; }
        public string Branch_ID { get; set; }
        public string Branch_Name { get; set; }
        public string Branch_Descriptiopn { get; set; }
        public string Status { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
